---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: k8s-version-distribution-check
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting pkg"
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: k8s-version-distribution-check.soumik.dev
    versionSelection:
      constraints: 1.0.0